### ISSUE TITLE
smoothWeightedRRLoadBalancer 是否有同步问题

### ISSUE THREAD

**Issue by hanzhihua** [sofastack/sofa-mosn#427]
我拜读了一下sofa-mosn的代码，关于smoothWeightedRRLoadBalancer 是否有数据同步问题呢？因为以前实现的wrr在修改effective,current weight里面是有一个lock的，请指教

**Comment by taoyuanyuan** [comment]
谢谢反馈，确实有这个问题

**Comment by nejisama** [comment]
WRR性能存在问题，暂时从实现从移除，后续会重新考虑实现
