### ISSUE TITLE
There is a  error when i run the examples with filter/commonrule

### ISSUE THREAD

**Issue by WywTed** [sofastack/sofa-mosn#656]
https://github.com/alipay/sofa-mosn/blob/master/examples/cn_readme/filter/commonrule/README.md

this page show how to use mosn to limit request. but there are errors when run.
~~~
2019/04/28 14:00:49 [ERROR] convert header from Http1 to Http2 failed, header type not supported
2019/04/28 14:00:49 [ERROR] Error on read. Connection = 55, Local Address = 127.0.0.1:2045,Remote Address = 127.0.0.1:42202, err = EOF
~~~

**Comment by WywTed** [comment]
use the latest build version 0.4.1.

**Comment by WywTed** [comment]
After i change all the  protocol to Http1, it can be invoke, but how to see it really limit ?
~~~
go run client.go -t 
~~~
it can return 200 always

**Comment by nejisama** [comment]
sorry, the example code just makes the mosn running.
if you want to test rate limit, you can use a http benchmark test tools to request mosn

**Comment by WywTed** [comment]
OK, thanks.
