### ISSUE TITLE
既然可以Auto协议，为什么xprotocol的sub不能auto，并且配置文件配置sub应该如何配

### ISSUE THREAD

**Issue by peacocktrain** [sofastack/sofa-mosn#678]
### Your question

describe your question clearly

### Environment
+ SOFAMosn Version

**Comment by nejisama** [comment]
协议自动识别只做了HTTP1和HTTP2的自动识别，其他协议都没有实现。
不同的协议有不同的细节，XProtocol更是可以扩展各种不同的协议，没有通用的协议自动识别

**Comment by nejisama** [comment]
{
  "type":"proxy",
  "config": {
    "downstream_protocol": "X",
    "upstream_protocol": "X",
    "router_config_name": "自定义",
    "extend_config": {
      "sub_protocol": "dubbo"
    }
  }
}

**Comment by taoyuanyuan** [comment]
协议自动识别是一个通用的框架,  支持最上层的协议自动识别, 目前就实现了 HTTP1和HTTP2.
比如HTTP2的实现, 主要就是判断首包的格式是否满足HTTP2协议规范.
```
func (f *streamConnFactory) ProtocolMatch(prot string, magic []byte) error {
	var size int
	var again bool
	if len(magic) >= len(http2.ClientPreface) {
		size = len(http2.ClientPreface)
	} else {
		size = len(magic)
		again = true
	}

	if bytes.Equal(magic[:size], []byte(http2.ClientPreface[:size])) {
		if again {
			return str.EAGAIN
		} else {
			return nil
		}
	} else {
		return str.FAILED
	}
}
```
Xprotocol有一点区别就是他包含了注册的子协议, 需要针对他支持的子协议做协议自动识别, 目前xprotocol没有做对应的代码实现, 我们近期会排期支持.
