### ISSUE TITLE
请问何时会完善文档呢？

### ISSUE THREAD

**Issue by xxm404** [sofastack/sofa-mosn#702]
### 关于项目文档的问题
请问何时会发布完善的文档呢？
是否支持 `Envoy` 的所有特性呢？比如主动 / 被动健康检查，`EDS` 服务发现等特性？
项目可否从 `Envoy` 平滑过渡到 `Mosn` ？

### Environment
+ SOFAMosn Version v0.5.0

**Comment by nejisama** [comment]
不清楚你说的完善的文档是什么
近期会发布一个mosn配置相关说明的文档。
mosn和envoy存在较多差异，不会是envoy的翻版

**Comment by nejisama** [comment]
主动健康检查默认已经实现基于TCP Dial的健康检查，可扩展实现别的健康检查
被动健康检查暂时没有实现，计划实现中
MOSN的Cluster具备动态更新的能力，与envoy不同的是没有具体区分CDS与EDS；MOSN有动态更新Cluster和动态更新Cluster中HOST的能力，但是具体的调用需要根据需求进行实现。其中部分在对接sofa-mesh中已经实现

**Comment by xxm404** [comment]
> 不清楚你说的完善的文档是什么
> 近期会发布一个mosn配置相关说明的文档。
> mosn和envoy存在较多差异，不会是envoy的翻版

这里指的就是关于配置的说明文档，因为没有文档，没有办法对 mosn 进行复制的配置
