### ISSUE TITLE
go-control-plane upgrade

### ISSUE THREAD

**Issue by JamazRuan** [sofastack/sofa-mosn#711]
### The New Feature
go-control-plane upgrade from version 0.4.0 to 0.6.3

### Your scenes
go-control-plane dependency upgrade and modify convertxds to support new features

### Your advice
Adapt to the SOFA Mesh new version can use the features of istio 1.1.4 such as sidecar CRD、exportTo attribute
ref: https://github.com/sofastack/sofa-mesh/issues/59

### Environment
0.5.0

**Comment by nejisama** [comment]
#480 duplicate
