### ISSUE TITLE
When will we support mosn as the ingress gateway?

### ISSUE THREAD

**Issue by oguchi-junko** [sofastack/sofa-mosn#757]
### Your question

describe your question clearly

Seems mosn is not able to act as the ingress gateway for now, when can we add this support in our roadmap?

### Environment
+ SOFAMosn Version

**Comment by nejisama** [comment]
mosn support ingress gateway.  we  run bookinfo example with ingress gateway。
see https://www.sofastack.tech/en/projects/sofa-mosn/quick-start-run-with-sofamesh/
