### ISSUE TITLE
The mosn agent another mosn uses the dubbo protocol to report an error.

### ISSUE THREAD

**Issue by lion-wang** [sofastack/sofa-mosn#766]
2019/08/07 09:43:10 [INFO] [2,-] [proxy] [upstream] connPool ready, proxyId = 1, host = 127.0.0.1:8000
2019/08/07 09:43:10 [DEBUG] [2,-] [proxy] [downstream] enter phase 5, proxyId = 1
2019/08/07 09:43:10 [DEBUG] [2,-] [proxy] [downstream] receive data = Ú»Â^@^@^@^@^@^@^@^@^@^@^@^@£^E2.0.20$com.demo.server.service.IDemoService^E0.0.0^Dtest^@H^Dpath0$com.demo.server.service.IDemoService     interface0$com.demo.server.service.IDemoService^Gversion^E0.0.0Z
2019/08/07 09:43:10 [DEBUG] [2,-] [proxy] [downstream] start a request timeout timer
2019/08/07 09:43:10 [DEBUG] [2,-] [proxy] [upstream] append data:Ú»Â^@^@^@^@^@^@^@^@^@^@^@^@£^E2.0.20$com.demo.server.service.IDemoService^E0.0.0^Dtest^@H^Dpath0$com.demo.server.service.IDemoService  interface0$com.demo.server.service.IDemoService^Gversion^E0.0.0Z
2019/08/07 09:43:10 [DEBUG] [2,-] [proxy] [downstream] enter phase 9, proxyId = 1
2019/08/07 09:43:10 [DEBUG] [2,-] [proxy] [downstream] waitNotify begin 0xc0000f2000, proxyId = 1
2019/08/07 09:43:12 [DEBUG] [network] [read loop] Error on read. Connection = 2, Local Address = 127.0.1.1:9000, Remote Address = 127.0.0.1:53577, err = EOF
2019/08/07 09:43:12 [DEBUG] [network] [close connection] Close TCP Conn, Remote Address is = 127.0.0.1:53577, eventType is = RemoteClose
2019/08/07 09:43:12 [DEBUG] [network] [close connection] Close connection 2, event RemoteClose, type NoFlush
2019/08/07 09:43:12 [ERROR] [normal] [2,-] [proxy] [downstream] processError=downstreamReset proxyId: 1
2019/08/07 09:43:12 [ERROR] [normal] [2,-] [proxy] [downstream] upstreamRequest.resetStream, proxyId: 1

**Comment by taoyuanyuan** [comment]
please upload server log.

**Comment by lion-wang** [comment]
[default-client.log](https://github.com/sofastack/sofa-mosn/files/3475552/default-client.log)

**Comment by taoyuanyuan** [comment]
the server log that listen 8000

**Comment by lion-wang** [comment]
like this :dubbo server listen 6050 <-mosn listen 8000 <-mosn listen 9000 <-dubbo client

**Comment by lion-wang** [comment]
this log is mosn listen 9000

**Comment by taoyuanyuan** [comment]
yes, upload this log listen 8000

**Comment by lion-wang** [comment]
[default.log](https://github.com/sofastack/sofa-mosn/files/3475661/default.log)

**Comment by taoyuanyuan** [comment]
you run client and server mosn on the same machine？
the second mosn will close the first mosn

**Comment by lion-wang** [comment]
OK,i change machine
