### ISSUE TITLE
Doesn't support OutlierDetection?

### ISSUE THREAD

**Issue by zhengzepeng** [sofastack/sofa-mosn#772]
看了下代码，把OutlierDetection那块处理给注释掉了

**Comment by nejisama** [comment]
之前也就是保留了配置，没有实现完全的，所以注释掉了。后面重新实现的时候再补回来

**Comment by zhengzepeng** [comment]
> 之前也就是保留了配置，没有实现完全的，所以注释掉了。后面重新实现的时候再补回来

明白了～感谢解答
