### ISSUE TITLE
metrics didn't correctly exposed with prometheus sink

### ISSUE THREAD

**Issue by teitoku-kento** [sofastack/sofa-mosn#781]
### Describe the bug

Use a httpbin service as backend. Config mosn with the setting below:

```json
{
  "servers": [
    {
      "default_log_path": "stdout",
      "default_log_level": "TRACE",
      "listeners": [
        {
          "name": "httpbin",
          "address": "0.0.0.0:8888",
          "bind_port": true,
          "log_path": "stdout",
          "filter_chains": [
            {
              "filters": [
                {
                  "type": "proxy",
                  "config": {
                    "downstream_protocol": "Http1",
                    "upstream_protocol": "Http1",
                    "router_config_name": "httpbin"
                  }
                },
                {
                  "type": "connection_manager",
                  "config": {
                    "router_config_name": "httpbin",
                    "virtual_hosts": [
                      {
                        "name": "httpbin",
                        "domains": [
                          "*"
                        ],
                        "routers": [
                          {
                            "match": {
                              "prefix": "/"
                            },
                            "route": {
                              "cluster_name": "httpbin",
                              "retry_policy": {
                                "retry_on": true,
                                "retry_timeout": "0s"
                              },
                              "timeout": "0s"
                            }
                          }
                        ]
                      }
                    ]
                  }
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "cluster_manager": {
    "clusters": [
      {
        "Name": "httpbin",
        "type": "SIMPLE",
        "lb_type": "LB_ROUNDROBIN",
        "max_request_per_conn": 1024,
        "conn_buffer_limit_bytes": 32768,
        "hosts": [
          {
            "address": "172.16.243.128:65535"
          }
        ]
      }
    ]
  },
  "metrics": {
    "flush_interval": "500ms",
    "sinks": [
      {
        "type": "prometheus",
        "config": {
          "port": 9542
        }
      }
    ]
  }
}
```

as the content shows, there is prometheus metric sink configed. And mosn logs like this:
![image](https://user-images.githubusercontent.com/54266028/63251291-00790d80-c2a0-11e9-8436-bfb43e68bf4e.png)
saying I'm serving prometheus metrics now.

Then, make some calls through mosn to the httpbin.

### Expected behavior

GET http://127.0.0.1:9542/metrics, got something like `cluster_host_upstream_request_total` with value not `0`

### Actual behavior

There was even no the related metric at all.

![image](https://user-images.githubusercontent.com/54266028/63251537-8432fa00-c2a0-11e9-8fd5-6a2028625e7f.png)

### Steps to reproduce

As described above.

### Environment
+ SOFAMosn Version

**Comment by teitoku-kento** [comment]
I tried comment out this line:
https://github.com/sofastack/sofa-mosn/blob/4df4c8284890c3f73d50f77279480cf69d1ae861/pkg/metrics/sink/prometheus/prometheus.go#L91
and metrics did exposed.

**Comment by nejisama** [comment]
i tried your config, and found if i use "curl" command i can get the metrics. but if i request in chrome, no metrics output.
@neverhook

**Comment by neverhook** [comment]
Thanks for your report. Just as @nejisama said, we found the problem was caused by the inappropriate gzip processing in prometheus sink. 

Considering the cost and priority of complete support for this, we decided to remove this feature support for the time being. See this PullRequest #787 for more detail.
