### ISSUE TITLE
What's the purpose of using buffer pool

### ISSUE THREAD

**Issue by teitoku-kento** [sofastack/sofa-mosn#797]
### Your question

describe your question clearly

[profile.tar.gz](https://github.com/sofastack/sofa-mosn/files/3540246/profile.tar.gz)

![image](https://user-images.githubusercontent.com/54266028/63677881-97097980-c820-11e9-85a6-83389762014f.png)

I tried rendering a cpu timing profile to a flame graph. Found that most latency is caused by io (read / write), what is not easy to avoid.

But I also noticed that `onNewStreamDetected` ate up about `6.35%` cpu times. I then have a glance at the code, it gets `proxyBuffersByContext` from within a pool which requires mutex internally. I guess this may slow request down if mosn serves many requests at one time.

Will allocate new object rather than taking from a pool be another option?

### Environment
+ SOFAMosn Version

**Comment by taoyuanyuan** [comment]
Mainly to reduce the number of temporary objects, reduce GC pressure
Pros and cons， Go Runtime Always optimizing sync.Pool.
the commit Optimized lock https://github.com/golang/go/commit/d5fd2dd6a17a816b7dfd99d4df70a85f1bf0de31#diff-491b0013c82345bf6cfa937bd78b690d
