### ISSUE TITLE
Doesn't support rbac?

### ISSUE THREAD

**Issue by zhengzepeng** [sofastack/sofa-mosn#803]
### Your question

SofaMosn doesn't support rbac?If support,how to use it?

### Environment
+ SOFAMosn Version

**Comment by nejisama** [comment]
we use a stream filter for rbac, but it still in experience, so the rbac in sofa-mosn will be supported later.

**Comment by zhengzepeng** [comment]
> we use a stream filter for rbac, but it still in experience, so the rbac in sofa-mosn will be supported later.

Thanks~
