### ISSUE TITLE
ask the path in make build-local command 

### ISSUE THREAD

**Issue by liyork** [sofastack/sofa-mosn#824]
### Your question

i run the command:
make build-local

bug get 
CGO_ENABLED=0 go build\
		-ldflags "-B 0x022552f34d421ecd55862c44c9cca170fa6348bf -X main.Version=0.7.0(a34f2e6d)" \
		-v -o mosnd \
		sofastack.io/sofa-mosn/cmd/mosn/main
can't load package: package sofastack.io/sofa-mosn/cmd/mosn/main: cannot find package "sofastack.io/sofa-mosn/cmd/mosn/main" in any of:
	/xxx/go/src/sofastack.io/sofa-mosn/cmd/mosn/main (from $GOROOT)
	/xxx/go/src/sofastack.io/sofa-mosn/cmd/mosn/main (from $GOPATH)
make: *** [build-local] Error 1

I find the question may be in Makefile
```PROJECT_NAME    = sofastack.io/sofa-mosn```

so if fix the quick start?

good luck.

### Environment
+ SOFAMosn Version

**Comment by nejisama** [comment]
already fixed.
