### ISSUE TITLE
Can help give pointers to the virtual machine mosn constantly print a log code where

### ISSUE THREAD

**Issue by carolove** [sofastack/sofa-mosn#831]
我发现虚拟机mosn的日志 /var/log/istio/istio.log中不断的打印类似于下面的log
2019/09/26 19:50:33.517 0s 0s 60.526µs 0 0 - 404 69.51µs false 404 - - - -
2019/09/26 19:50:34.525 0s 0s 105.853µs 0 0 - 404 115.375µs false 404 - - - -
2019/09/26 19:50:35.532 0s 0s 74.947µs 0 0 - 404 83.711µs false 404 - - - -
2019/09/26 19:50:36.541 0s 0s 96.852µs 0 0 - 404 110.912µs false 404 - - - -
2019/09/26 19:50:37.436 116.564µs 1.720031ms 1.75678ms 27 1296 - 200 1.766405ms false 200 172.31.107.216:8848 127.0.0.1:15001 10.100.34.46:8848 -

能够帮忙指正一下这个日志的代码在那个地方吗？

**Comment by khotyn** [comment]
看起来这个是 Istio 的日志而不是 SOFAMosn 的日志。
