### ISSUE TITLE
tcpproxy example error

### ISSUE THREAD

**Issue by g5niusx** [sofastack/sofa-mosn#856]
### Describe the bug

in https://github.com/sofastack/sofa-mosn/blob/becc7a6dc50c4df322416c06af9630f6ed7954b6/examples/codes/tcpproxy-sample/rpc_client.go#L72
`Instance ` undefined `Serialize ` method..

### Environment
+ SOFAMosn 0.7.0

**Comment by sqtds** [comment]
你提交修复吗？或者我改下？

**Comment by nejisama** [comment]
应该是代码重构忽略了example的代码，你先改一下吧
