### ISSUE TITLE
sofarpc and HTTP2 protocol ？

### ISSUE THREAD

**Issue by woshioosm** [sofastack/sofa-mosn#859]
example 文档中 https://github.com/sofastack/sofa-mosn/tree/master/examples/cn_readme/sofarpc-sample

使用 SOFAMosn 作为 SOFARPC 代理
简介
该样例工程演示了如何配置使得SOFAMosn作为SofaRpc代理
SOFAMosn之间的协议是HTTP2
为了演示方便，SOFAMosn监听两个端口,一个转发Client的请求，一个收到请求以后转发给Server
。。。。。。

有个疑问
传统的sofarpc为 tcp协议
 使用sofarpc 协议时   mosn之间为何是 http2 协议？ 而不采用 tcp proxy？

**Comment by nejisama** [comment]
HTTP2协议只是演示一个协议转换，一般也没有这个需求
实际大多数配置都是sofarpc-sofarpc 而不是sofarpc-http2
tcp proxy支持的功能有限，一般明确的场景都用proxy比较好

**Comment by nejisama** [comment]
使用sofarpc-sofarpc的场景，可以client/server 只要有一端接入了mosn就可以，是最常见的场景。

**Comment by woshioosm** [comment]
@nejisama 非常感谢解答
