### ISSUE TITLE
Why does package management choose dep instead of vgo?

### ISSUE THREAD

**Issue by russellgao** [sofastack/sofa-mosn#868]
### Your question

sofa-mosn 包管理使用dep 管理，请问是基于什么考量选择dep 而不是基于 vgo ，感觉使用vgo 更方便一些?

### Environment
0.8.0

**Comment by nejisama** [comment]
最开始mosn基于1.9开发，go mod（vgo）也还不是默认的。
另外就是做CI的时候还是依赖vendor目录
后面会考虑使用go mod，但是vendor目录依然会保留
