### ISSUE TITLE
go mod reference mosn report an error

### ISSUE THREAD

**Issue by peacocktrain** [sofastack/sofa-mosn#887]
### Describe the bug
go mod require sofastack.io/sofa-mosn v0.0.0-20191125121549-e3e11830cfca

# error
 sofastack.io/sofa-mosn/pkg/api/v2
/Users/fuzesun/go/pkg/mod/sofastack.io/sofa-mosn@v0.0.0-20191125121549-e3e11830cfca/pkg/api/v2/types.go:29:2: imported and not used: "github.com/envoyproxy/go-control-plane/envoy/api/v2/auth" as envoy_api_v2_auth
/Users/fuzesun/go/pkg/mod/sofastack.io/sofa-mosn@v0.0.0-20191125121549-e3e11830cfca/pkg/api/v2/types.go:399:10: undefined: auth

**Comment by nejisama** [comment]
we use dep not vgo.
the package "go-control-plane/envoy/api/v2/auth" contains "v2" in the package name, so it needs to rename the package, but we do not adapt for it.
```
import (
envoyauth "github.com/envoyproxy/go-control-plane/envoy/api/v2/auth" 
)
```

**Comment by peacocktrain** [comment]
I want to use mosn to fit the istio proxy，this report must be resolved 。 please do it。
